### ISSUE TITLE
hi i was wondering what version of openal did you use?

### ISSUE THREAD

**Issue by JonnycatMeow** [Leather128/hxopenal#2]
did you use this? https://github.com/kcat/openal-soft

**Comment by Leather128** [comment]
yes that is the version of openal-soft that is used for this project.

**Comment by JonnycatMeow** [comment]
the master branch?

**Comment by JonnycatMeow** [comment]
or the current release?

**Comment by Leather128** [comment]
the current latest release is what is being used, why do you ask?

**Comment by JonnycatMeow** [comment]
oh cause i am gonna make the macos lib for you

**Comment by JonnycatMeow** [comment]
it's gonna be static lib not a dynamic lib or as they call it a "shared" lib

**Comment by Leather128** [comment]
alright, thanks

**Comment by JonnycatMeow** [comment]
no problem
