### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'OpenAL32.lib'

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [Leather128/hxopenal#9]
I set up everything. What the hell should I do?

**Comment by Leather128** [comment]
How did you exactly set it up? (I'm going to archive this library after this issue as you should be using [hxal](https://github.com/swordcube/hxal) since it's more up to date)

**Comment by SomeGuyWhoLovesCoding** [comment]
> How did you exactly set it up? (I'm going to archive this library after this issue as you should be using [hxal](https://github.com/swordcube/hxal) since it's more up to date)

Through the readme's installation section

**Comment by Leather128** [comment]
Odd, I'm not entirely sure what broke since I haven't worked on this in a while, so I think trying to move to [hxal](https://github.com/swordcube/hxal) would be your best bet. Especially considering it's literally just a fork of this project that's more up to date and maintained. Closing.
